name: Workflows Test
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
jobs:
  workflows-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out
        uses: actions/checkout@v2.3.4
      - name: Testing the default configuration
        uses: ./
      - name: Testing with different distribution
        uses: ./
        with:
          ros2-distro: rolling
          image-name: ros
      - name: Testing with including external repositories
        uses: ./
        with:
          ros2-distro: foxy
          external-repos: https://github.com/ros2/example_interfaces#foxy ros2/examples#foxy
